title: Your Awesome Site
author:
        name: 物灵
        email: mat-ling@139.com
description:
lang: cmn-Hans

theme-2038:
        wordmark: /assets/wordmark.svg
        from-year: 2038
        footer-desc: default-slogan
#        license: Some license
        social:
#               github: 0xis-cn 
#               instagram: mat__ling
#               telegram: cn_0xis
        drawer-links:
#                -
#                       name: category
#                       url: /category
#               -
#                       name: tag
#                       url: /tag
        footer-links:
#               -
#                       name: { cmn-Hans: 中文名, default: English name }
#                       url: https://www.example.com
#               -
#                       name: One name for all languages
#                       url: https://www.example.org

highlighter: rouge
markdown: kramdown
kramdown:
        input: GFM
        syntax_highlighter: rouge

